### ISSUE TITLE
Can't grab data

### ISSUE THREAD

**Issue by shipcommit** [Mithrandir2k18/dockerized-https-ipfs-gateway#1]
Interesting project you have here, it would be so much easier to set up an IPFS gateway if I can get this working.

How long do I have to wait before receiving IPFS test data? I got it working first time I ran the script, but after cloning the repository several times, and entering my domain and email in all the right places, it doesn't seem like I'm getting anything.

```
Now let's also test if we can grab some data. You should see a greeting printed to the screen next!
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:39:15 --:--:--     0
```

**Comment by Mithrandir2k18** [comment]
The script starts a docker container running your ipfs-node. If you run the script multiple times, there might be an issue with multiple containers attempting to bind to the same port. Using `docker ps` you can check the status of your containers. Alternatively just `cd /path/to/repo` and from there do `docker-compose down` which should bring down all containers relevant to this repo.

Why are you running the script/repo several times? It is intended to be ran once, after that the containers will automatically restart after each boot or crash, since in the `docker-compose.yaml` the services are configured to restart unless expclicitly stopped with e.g. `docker-compose down`.
